### ISSUE TITLE
Python 3.7+ support

### ISSUE THREAD

**Issue by dekoza** [rienafairefr/python-ldraw#2]
Right now this library is marked as not supporting Python 3.7 and above and this makes [poetry](https://python-poetry.org/) not to install it:

```
[SolverProblemError]
The current project's Python requirement (^3.8) is not compatible with some of the required packages Python requirement:
  - pyldraw requires Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, <3.7
```

Is there anything that prevents it from running under Python 3.7 and above or was this just a precaution?

**Comment by rienafairefr** [comment]
I think nothing really prevents it from running under python 3.7 and above, py37 probably wasn't even released when it was written.
Your PR adds it fine I think, but the CI puked errors. I'll get on it

**Comment by dekoza** [comment]
Thanks. Tox failed for me locally even on older Python version so it might be caused by one/some of the dependencies being updated too.

**Comment by dekoza** [comment]
OK, I've updated the test data so now tests for my PR should pass. Seeing the "uncomment to save" entries in tests hinted me that these problems already happened before :wink:

**Comment by rienafairefr** [comment]
There is some snapshot testing done, to verify that output for ldr2inv, ldr2png etc remains the same for given inputs. If the snapshot has to change, we can change it by uncommenting that part. It's not the cleanest part of the cod, because I didn't guard agains the ldraw library updating (which changes the outputs, even if the code doesn't change), I'll have to fix that.
